Console.Clear();
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("Preparar...");
Console.ResetColor();
Console.ReadKey();
Console.Clear();
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("Apontar...");
Console.ResetColor();
Console.ReadKey();
Console.Clear();
Console.BackgroundColor = ConsoleColor.Green;
Console.Beep(1759, 500);
Console.WriteLine("Fogo!");
Console.ResetColor();
Console.ReadKey();
Console.Clear();